// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    EmployeeDataTable: typeof import('./src/components/EmployeeDataTable.vue')['default']
    EmployeeDataTableRow: typeof import('./src/components/EmployeeDataTableRow.vue')['default']
    ExportAsCSVButton: typeof import('./src/components/ExportAsCSVButton.vue')['default']
    FileUpload: typeof import('./src/components/FileUpload.vue')['default']
    Header: typeof import("./src/layouts/Header.vue")["default"]
    Home: typeof import('./src/layouts/Home.vue')['default']
    OutlineButton: typeof import('./src/components/OutlineButton.vue')['default']
    PrimaryButton: typeof import('./src/components/PrimaryButton.vue')['default']
  }
}
